### ISSUE TITLE
fix pager of first post to vakantiewerk

### ISSUE THREAD

**Issue by olbrew** [eestec-antwerp/eestec-antwerp.github.io#4]
First post has a previous post pager pointing to vakantiewerk. As vakantiewerk is a menu item, the first post obviously shouldn't point to this.

**Comment by EESTEC-Antwerp-Admin** [comment]
The more articles there are, the less of a problem this is :smile:

**Comment by olbrew** [comment]
Shouldn't be a difficult fix actually 😅. Now the [first post](http://www.eestec.be/post/welcomeagain/) will always have a pager item to the next post/page. Should be solved by fixing the template to differ between pages and posts so the `vakantiewerk page` is not identified as a post anymore.

**Comment by olbrew** [comment]
Wrong repo
